name: "Build Reference Implementation"

on:
  push:
    branches:
      - main
    paths:
      - reference-implementation/**
  pull_request:
    branches:
      - main
    paths:
      - reference-implementation/**

jobs:
  build:
    name: "Build Reference Implementation"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Build reference implementation"
      run: |
        cd reference-implementation
        cargo test

    - name: "Verify JSON test vectors"
      run: |
        cd reference-implementation
        cargo run --example test_vectors verify <../test-vectors/test-vectors.json

    - name: "Verify that Markdown test vectors are unmodified"
      run: |
        ./make-test-vectors.sh
        if [[ `git status --porcelain` ]]
        then 
          exit 1
        fi
